services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sheepdog_network

  sheepdog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sheepdog
    ports:
      - "80:80"
    volumes:
      - ./creds.json:/var/www/sheepdog/creds.json
      - ./sheepdog/bin/confighelper.py:/var/www/sheepdog/bin/confighelper.py
      - ./sheepdog/bin/settings.py:/var/www/sheepdog/bin/settings.py
    environment:
      - DATABASE_URL=postgres://postgres:test@postgres:5432/postgres
    networks:
      - sheepdog_network
    depends_on:
      - postgres

networks:
  sheepdog_network:

volumes:
  postgres_data:


## docker exec -it sheepdog bash
# apt-get update && apt-get install -y postgresql-client

## psql -h postgres -U postgres -d postgres

## service postgresql status
## service postgresql start